spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: "jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul"
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8097

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/