spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: article
          predicates:
            - Path=/article/**
          uri: lb://ARTICLE
          filters:
            - RewritePath=/article/(?<segment>.*), /${segment}
        - id: authentication
          predicates:
            - Path=/authentication/**
          uri: lb://AUTHENTICATION
          filters:
            - RewritePath=/authentication/(?<segment>.*), /${segment}
        - id: kitcha-board
          predicates:
            - Path=/kitcha-board/**
          uri: lb://KITCHA-BOARD
          filters:
            - RewritePath=/kitcha-board/(?<segment>.*), /${segment}
server:
  port: 8072
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
token:
  secret: My JWTToken's Secret is p@ssw0rd
