spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul"
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

token:
  expiration-time: 86400000
  secret: "My JWTToken's Secret is p@ssw0rd"